---
Standards:
  -
    Title: Intro To Web Development
    Description: "Web Applications and Layers, Intro to Clients, Servers, HTTP, Sequence Diagrams, Request-Response Cycle Activity: Layers"
    UID: 87ee542387da94693acb5efb099b7f58
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: c674f6dd20d7be77cfb94798b04ba3b7
        Path: /intro-to-web-development/intro-to-web-development.instructor.md
      -
        Type: Lesson
        UID: fb82af67544ea4e47867dacf14422750
        Path: /intro-to-web-development/web-applications-and-layers.md
      -
        Type: Lesson
        UID: 3b85293903e714dbf08ba517f828ac88
        Path: /intro-to-web-development/intro-to-clients-servers-http.md
      -
        Type: Lesson
        UID: 0cb41fed41e0e32dfb1adbd4b5d61c9a
        Path: /intro-to-web-development/sequence-diagrams.md
      -
        Type: Lesson
        UID: 725ecafa914bb1b7bd4f47a305398ae8
        Path: /intro-to-web-development/request-response-cycle.md
      -
        Type: Lesson
        UID: 50ce8362260e6524b31d9c6a8c990c2c
        Path: /intro-to-web-development/activity-layers.md
  -
    Title: Requests And Responses in Postman and Python
    Description: "Sending Requests from Postman, API Keys, Sending Requests With Python, Problem Set: Requests With Python, Activity: Web API Jigsaw"
    UID: b33d004935f89cb3dc27032aed9a1971
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 4e147331c0920ff789c815744d162587
        Path: /requests-and-responses/problem-set-requests-with-python.instructor.md
      -
        Type: Lesson
        UID: 36352066c1e128d38ee834fb0db51513
        Path: /requests-and-responses/sending-requests-from-postman.md
      -
        Type: Lesson
        UID: 0bf2679dc61b68a5d8683c021f5e5621
        Path: /requests-and-responses/api-keys.md
      -
        Type: Lesson
        UID: 3ce410c74f7c810715f9982420878886
        Path: /requests-and-responses/sending-requests-with-python.md

      -
        Type: Lesson
        UID: 3c6844408261fe7c7d50f7dc4dc2c447
        Path: /requests-and-responses/problem-set-requests-with-python.md
      -
        Type: Lesson
        UID: 2f8f732d3d523c2302f4568e519bcbff
        Path: /requests-and-responses/activity-web-api-jigsaw.md
  -
    Title: Intro To API Design
    Description: "Designing Endpoints, Designing Responses, Problem Set: Intro to API Design, Activity: Intro to API Design"
    UID: 0c5f68ba66d52eba25ba51327ee89b88
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 9844bca7c230e2bf7ded06c1c8157d12
        Path: /intro-to-api-design/intro-to-api-design.instructor.md
      -
        Type: Lesson
        UID: ba2ee66f047cf534ff691b8412da3332
        Path: /intro-to-api-design/designing-endpoints.md
      -
        Type: Lesson
        UID: 82f2c31b30d0ec23865311d32a45f02e
        Path: /intro-to-api-design/designing-responses.md
      -
        Type: Lesson
        UID: 8WFdaq
        Path: /intro-to-api-design/problem-set-intro-to-api-design.md
      -
        Type: Lesson
        UID: 5f9a641756dea1f4bc8a5c1776d46528
        Path: /intro-to-api-design/activity-intro-to-api-design.md
  -
    Title: 01) Building an API - Intro to Flask, Setup, and Read
    Description: "Intro to Flask, Intro to Hello Books, Flask Setup, Hello World, Read All Books"
    UID: dea859c0
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 6b5e64fa-93af-476a-82aa-521bc696065d
        Path: /api-1-setup-read/activity-solar-system-api.instructor.md
      -
        Type: Lesson
        UID: e77cd6b2788d0e9d3a585da004982bda
        Path: /api-1-setup-read/intro-to-flask.md
      -
        Type: Lesson
        UID: ecc66e53-6e24-4fd8-ab9a-555a4087d222
        Path: /api-1-setup-read/intro-to-hello-books.md
      -
        Type: Lesson
        UID: e89e0215704779b45a29307ae4e880be
        Path: /api-1-setup-read/flask-setup.md
      -
        Type: Lesson
        UID: 34723e00ee31eff079c37b5c7e89822f
        Path: /api-1-setup-read/hello-world-routes.md
      -
        Type: Lesson
        UID: 80decfe5-2fd1-45ee-9855-efe05da959d2
        Path: /api-1-setup-read/read-all-books.md
      -
        Type: Lesson
        UID: aefff6c0-6dde-4470-8069-65025f89b66d
        Path: /api-1-setup-read/problem-set-setup-read.md
      -
        Type: Instructor
        UID: 6e0b2738-99c1-44f6-96c3-f17aaea55fcb
        Path: /api-1-setup-read/activity-solar-setup-read.md
      -
        Type: Resource
        UID: 2b5c17c9-4e58-4182-acb5-09d5260faefc
        Path: /api-1-setup-read/m1-mac-psycopg2-fix.resource.md 
  -
    Title: 02) Building an API - Read and Errors
    Description: "Read One Book, Error Handling"
    UID: 58e6e2cb-3060-48f8-abf2-0df2986f07ae
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 66500b39-f5e6-4ac3-bb00-5978cdfc2450
        Path: /api-2-read-404s/read-one-book.md
      -
        Type: Lesson
        UID: dce109b9-20f8-4827-8d10-eeffab3c2de0
        Path: /api-2-read-404s/400-and-404s.md
      -
        Type: Lesson
        UID: 470465db-89a3-4535-a154-7e7391ef4d93
        Path: /api-2-read-404s/problem-set-read-404s.md
      -
        Type: Instructor
        UID: 8ac983dc-e8a4-492c-8149-df4d0458add8
        Path: /api-2-read-404s/activity-solar-read-404s.md
  -
    Title: Data In Tables
    Description: "Data in Tables, Intro to Relational Databases, Activity: Data in Tables"
    UID: f7c302282a7e78968f846372a19f50ef
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 50c412213820ae1e7ffd5a432f8a2fb7
        Path: /data-in-tables/data-in-tables.instructor.md
      -
        Type: Instructor
        UID: 62c24181bff87815cf3039e30c8c32b2
        Path: /data-in-tables/instructor-activity-data-in-tables.md
      -
        Type: Instructor
        UID: paZju7
        Path: /intro-to-sql/intro-to-relational-databases.instructor.md
      -
        Type: Lesson
        UID: 0e1f2fc10fdeffcb430193b38662480e
        Path: /data-in-tables/data-in-tables.md
      -
        Type: Lesson
        UID: bf845a0d8d9b36277b4a65ad5a323ec6
        Path: /intro-to-sql/intro-to-relational-databases.md
      -
        Type: Lesson
        UID: a5d0460ebba87354036cecef3e810940
        Path: /data-in-tables/activity-data-in-tables.md
  -
    Title: Intro To SQL
    Description: "SQL Setup, Adding New Records, Retrieving Records, Updating Records, Deleting Records, Problem Set: Intro to SQL, Activity: Intro to SQL"
    UID: 3211fc3d75369f96b537a4535fcbba6d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d208cde984a0236f321a3a2216132286
        Path: /intro-to-sql/intro-to-sql.instructor.md
      -
        Type: Lesson
        UID: 9f6237c34cd80959b46a2a6b197e04f5
        Path: /intro-to-sql/sql-setup.md
      -
        Type: Lesson
        UID: 5166b21899f0663aace050ca240e65c4
        Path: /intro-to-sql/adding-new-records.md
      -
        Type: Lesson
        UID: 9bd533be21a9cc9981797c67b9991514
        Path: /intro-to-sql/retrieving-records.md
      -
        Type: Lesson
        UID: 17054b670dbade2badeca1263766c075
        Path: /intro-to-sql/updating-records.md
      -
        Type: Lesson
        UID: 66c659ae-9887-4e01-a059-a73b22847a5d
        Path: /intro-to-sql/deleting-records.md
      -
        Type: Lesson
        UID: tTqwLh
        Path: /intro-to-sql/problem-set-intro-to-sql.md
      -
        Type: Instructor
        UID: 431e288ed7b0fa2b88b7599ae09a3543
        Path: /intro-to-sql/activity-intro-to-sql.instructor.md
      -
        Type: Lesson
        UID: 1ccd31d7b789d74e78d94c236193bb8d
        Path: /intro-to-sql/activity-intro-to-sql.md
  -
    Title: Relationships in SQL
    Description: "Database Relationships, Establishing Relationships, Problem Set: Intermediate SQL"
    UID: 11a8027f-bd04-4c47-b4d3-36209af1068d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c8e5656f-6fd9-43fa-8c30-164c4da593b8
        Path: /relationships-in-sql/database-relationships.md
      -
        Type: Lesson
        UID: a00c1cf2-cb0c-440b-bb5b-188ab64628ea
        Path: /relationships-in-sql/establishing-relationships.md
      -
        Type: Lesson
        UID: d23c9ef5-1e99-4057-93ef-8863f33be45f
        Path: /relationships-in-sql/database-joins.md
      -
        Type: Lesson
        UID: cbd53d1c-3374-4a55-804b-85defb26bd4b
        Path: /relationships-in-sql/problem-set-intermediate-sql.md
  -
    Title: (Optional) More Selecting In SQL
    Description: "Compound Conditions, Ordering, Limit, Problem Set: More Selecting in SQL"
    UID: 29f75f91-0453-468c-a724-d6b90a045e6a
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 0cbd2906-19c9-4983-83b0-d1e8620ed879
        Path: /more-selecting-in-sql/compound-conditions.md
      -
        Type: Lesson
        UID: ec61db9d-17e7-4aff-ae18-904c13cdb8cd
        Path: /more-selecting-in-sql/ordering.md
      -
        Type: Lesson
        UID: f17bddc5-338d-4077-b4fe-5e9764000b87
        Path: /more-selecting-in-sql/limit.md
      -
        Type: Lesson
        UID: f9f13580-bd04-442a-8944-34864f3de6a2
        Path: /more-selecting-in-sql/problem-set-more-selecting-in-sql.md
      -
        Type: Lesson
        UID: 7b23e0bb-64ea-4f55-aca4-4502d9f8e7fb
        Path: /more-selecting-in-sql/aggregate-functions.md
      -
        Type: Lesson
        UID: af18e4ef-18aa-432c-9f34-0375f4dbb82a
        Path: /more-selecting-in-sql/grouping.md
      -
        Type: Lesson
        UID: 139ef877-f6ea-4455-8cad-e42849c19bf8
        Path: /more-selecting-in-sql/modifying-tables-in-sql.md
      -
        Type: Lesson
        UID: eed7f313-69fe-4881-9b7c-829860adeb4e
        Path: /more-selecting-in-sql/modifying-databases-in-sql.md
  -
    Title: 03) Building an API - Database, Models, Create, and Read 
    Description: "Introduction to Models and Migrations, Models Setup, Create, Read"
    UID: 2804d58bb38264215b9414a111a759d7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: fc3e20f36128c5fb1e97ab0b40553094
        Path: /api-3-database-models-read/models-migrations.md
      -
        Type: Lesson
        UID: dcd0d3c276356844a38f890d5a9b98c9
        Path: /api-3-database-models-read/models-setup.md
      -
        Type: Lesson
        UID: 2ca35886fc1a00a394384b7d88b9b2b8
        Path: /api-3-database-models-read/create.md
      -
        Type: Lesson
        UID: 31ce9cf5-9f15-455c-8992-99f08172c506
        Path: /api-3-database-models-read/read-all-books.md
      -
        Type: Lesson
        UID: 5f4dda242707c828aa5dbd99e73fe62b
        Path: /api-3-database-models-read/problem-set-create-read.md
      -
        Type: Instructor
        UID: m9dgD0
        Path: /api-3-database-models-read/activity-solar-create-read.md
      -
        Type: Resource
        UID: e50fdece-7024-4bce-9523-0eff1f35e70c
        Path: /api-3-database-models-read/m1-mac-psycopg2-fix.resource.md  
  -
    Title: 04) Building an API - Read, Update, And Delete
    Description: "Read, Update, and Delete"
    UID: c806ada4c97ac6c20ee838c607c979d7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 8c8f1381-c8ef-4859-aa05-d04e8c7392fa
        Path: /api-4-read-update-delete/read-one-book-2.md
      -
        Type: Lesson
        UID: 43e557f3-3455-4962-af38-43a23d57893f
        Path: /api-4-read-update-delete/update.md
      -
        Type: Lesson
        UID: eebc0514b2efcba42ff925c17aa17fde
        Path: /api-4-read-update-delete/delete.md
      -
        Type: Lesson
        UID: syrMq6
        Path: /api-4-read-update-delete/problem-set-read-update-delete.md
      -
        Type: Instructor
        UID: etO5RZ
        Path: /api-4-read-update-delete/activity-solar-read-update-delete.md
  -
    Title: 05) Building an API - More Flask Queries
    Description: "Query Params"
    UID: OkfzUG
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: HfbxKc
        Path: /api-5-more-queries/query-params.md
      -
        Type: Instructor
        UID: 2cfe7232-9dd4-4efe-8d33-9a4539ec3c63
        Path: /api-5-more-queries/activity-solar-refactor.md
  -
    Title: 06) Building an API - Testing
    Description: "Environments and Env Vars, dotenv and the Test DB, Fixtures, Test Setup, GET /books, GET /books/<book_id>, POST /books"
    UID: e7cb1f63923b38e37e787f78784653ec
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c49f1e46b7e1f26263c71173af781cea
        Path: /api-6-testing/environments-and-env-vars.md
      -
        Type: Lesson
        UID: f153ea3be2591354fccbc62912327060
        Path: /api-6-testing/dot-env-and-the-test-db.md
      -
        Type: Lesson
        UID: 8dfac72f68845ac31b3527aeba524c01
        Path: /api-6-testing/fixtures.md
      -
        Type: Lesson
        UID: ae6d7749089a176f86e664172c9c3102
        Path: /api-6-testing/test-setup.md
      -
        Type: Lesson
        UID: MAKii1
        Path: /api-6-testing/using-tests.md
      -
        Type: Lesson
        UID: 474170f0-3e8c-4c57-89a3-5bade315e300
        Path: /api-6-testing/read-one-book-test.md
      -
        Type: Lesson
        UID: 1a399481-d020-47d6-a6a5-9bb3199d53c1
        Path: /api-6-testing/post-books-test.md
      -
        Type: Lesson
        UID: 8TZO0e
        Path: /api-6-testing/problem-set-testing.md
      -
        Type: Instructor
        UID: L00UOa
        Path: /api-6-testing/activity-solar-testing.md
  -
    Title: 07) Building an API - One-to-Many Relationships
    Description: "One-to-Many Relationships, Nested Routes in Flask"
    UID: 11960148-2005-4ce6-b12d-c9f788667407
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 55cb7e64-9a4f-47f5-bc7d-162e38257f05
        Path: /api-7-relationships-in-sqlalchemy/one-to-many.md
      -
        Type: Lesson
        UID: 66f19557-3680-4552-bb9b-440ea22d0c20
        Path: /api-7-relationships-in-sqlalchemy/nested-routes-in-flask.md
  -
    Title: 08) Building an API - Deployment
    Description: "Deployment, Deploying to Heroku, Problem Set: Deployment, Activity: Deploying to Heroku"
    UID: ea355214fd4bc7c57f471bd92918879b
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 9e1096612d943453372431b09479429a
        Path: /api-8-deployment/deployment.instructor.md
      -
        Type: Lesson
        UID: d6dc45ac3fb4fec2cb1209ccf2ab53dc
        Path: /api-8-deployment/deployment.md
      -
        Type: Lesson
        UID: 2eccb3b5671761e4e6ea2f9f9e5cdf88
        Path: /api-8-deployment/deploying-to-heroku.md
      -
        Type: Lesson
        UID: 082a038b50122fe48f98c2338f822b2a
        Path: /api-8-deployment/problem-set-deployment.md
      -
        Type: Lesson
        UID: ee88de6f19748458e8539e3835f8c294
        Path: /api-8-deployment/activity-deploying-to-heroku.md
  -
    Title: 09) Building an API - Many-to-Many Relationships
    Description: "Many-to-Many: Genres, Many-to-Many: Books and Genres"
    UID: 47ca5247-b2f4-45c9-8d37-8ea43f0e86f8
    SuccessCriteria:
      - success criteria
    ContentFiles:
        -
          Type: Lesson
          UID: c672b599-4f30-44cc-8831-0cf91f17d63e
          Path: /api-9-many-to-many/many-to-many-genre.md
        -
          Type: Lesson
          UID: 3bb7e9d1-b7fa-4067-a404-8d77468b563e
          Path: /api-9-many-to-many/many-to-many-books-genres.md
  -
    Title: Unit Wrap Up
    Description: "Activity: Mind Map"
    UID: dndEGK
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: KSjccL
        Path: /unit-wrap-up/activity-mind-map.md