---
Standards:
  -
    Title: Data In Tables
    Description: "Data in Tables, Activity: Data in Tables"
    UID: f7c302282a7e78968f846372a19f50ef
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 50c412213820ae1e7ffd5a432f8a2fb7
        Path: /data-in-tables/data-in-tables.instructor.md
      -
        Type: Lesson
        UID: 0e1f2fc10fdeffcb430193b38662480e
        Path: /data-in-tables/data-in-tables.md
      -
        Type: Instructor
        UID: 62c24181bff87815cf3039e30c8c32b2
        Path: /data-in-tables/instructor-activity-data-in-tables.md      
      -
        Type: Lesson
        UID: a5d0460ebba87354036cecef3e810940
        Path: /data-in-tables/activity-data-in-tables.md
  -
    Title: Intro To SQL
    Description: "Intro to Relational Databases, SQL Setup, Adding New Records, Retrieving Records, Updating Records, Deleting Records, Problem Set: Intro to SQL, Activity: Intro to SQL"
    UID: 3211fc3d75369f96b537a4535fcbba6d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d208cde984a0236f321a3a2216132286
        Path: /intro-to-sql/intro-to-sql.instructor.md
      -
        Type: Instructor
        UID: paZju7
        Path: /intro-to-sql/intro-to-relational-databases.instructor.md
      -
        Type: Lesson
        UID: bf845a0d8d9b36277b4a65ad5a323ec6
        Path: /intro-to-sql/intro-to-relational-databases.md
      -
        Type: Lesson
        UID: 9f6237c34cd80959b46a2a6b197e04f5
        Path: /intro-to-sql/sql-setup.md
      -
        Type: Lesson
        UID: 5166b21899f0663aace050ca240e65c4
        Path: /intro-to-sql/adding-new-records.md
      -
        Type: Lesson
        UID: 9bd533be21a9cc9981797c67b9991514
        Path: /intro-to-sql/retrieving-records.md
      -
        Type: Lesson
        UID: 17054b670dbade2badeca1263766c075
        Path: /intro-to-sql/updating-records.md
      -
        Type: Lesson
        UID: 66c659ae-9887-4e01-a059-a73b22847a5d
        Path: /intro-to-sql/deleting-records.md
      -
        Type: Lesson
        UID: tTqwLh
        Path: /intro-to-sql/problem-set-intro-to-sql.md
      -
        Type: Instructor
        UID: 431e288ed7b0fa2b88b7599ae09a3543
        Path: /intro-to-sql/activity-intro-to-sql.instructor.md
      -
        Type: Lesson
        UID: 1ccd31d7b789d74e78d94c236193bb8d
        Path: /intro-to-sql/activity-intro-to-sql.md 
  -
    Title: Intermediate SQL
    Description: "Database Relationships, Establishing Relationships, Database Joins, Problem Set: Intermediate SQL"
    UID: 11a8027f-bd04-4c47-b4d3-36209af1068d
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c8e5656f-6fd9-43fa-8c30-164c4da593b8
        Path: /intermediate-sql/database-relationships.md
      - 
        Type: Lesson
        UID: a00c1cf2-cb0c-440b-bb5b-188ab64628ea
        Path: /intermediate-sql/establishing-relationships.md
      -
        Type: Lesson
        UID: d23c9ef5-1e99-4057-93ef-8863f33be45f
        Path: /intermediate-sql/database-joins.md
      -
        Type: Lesson
        UID: cbd53d1c-3374-4a55-804b-85defb26bd4b
        Path: /intermediate-sql/problem-set-intermediate-sql.md
  -
    Title: Intro To Web Development
    Description: "Web Applications and Layers, Intro to Clients, Servers, HTTP, Sequence Diagrams, Activity: Layers"
    UID: 87ee542387da94693acb5efb099b7f58
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c674f6dd20d7be77cfb94798b04ba3b7
        Path: /intro-to-web-development/intro-to-web-development.instructor.md
      -
        Type: Lesson
        UID: fb82af67544ea4e47867dacf14422750
        Path: /intro-to-web-development/web-applications-and-layers.md
      -
        Type: Lesson
        UID: 3b85293903e714dbf08ba517f828ac88
        Path: /intro-to-web-development/intro-to-clients-servers-http.md
      -
        Type: Lesson
        UID: 0cb41fed41e0e32dfb1adbd4b5d61c9a
        Path: /intro-to-web-development/sequence-diagrams.md
      -
        Type: Lesson
        UID: 50ce8362260e6524b31d9c6a8c990c2c
        Path: /intro-to-web-development/activity-layers.md
  -
    Title: Requests And Responses
    Description: "Request-Response Cycle, Sending Requests from Postman, API Keys, Sending Requests With Python, Problem Set: Requests With Python, Activity: Web API Jigsaw"
    UID: b33d004935f89cb3dc27032aed9a1971
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: f8718b982976e86f238c9e3b0af77636
        Path: /requests-and-responses/requests-and-responses.instructor.md
      -
        Type: Lesson
        UID: 725ecafa914bb1b7bd4f47a305398ae8
        Path: /requests-and-responses/request-response-cycle.md
      -
        Type: Lesson
        UID: 36352066c1e128d38ee834fb0db51513
        Path: /requests-and-responses/sending-requests-from-postman.md
      -
        Type: Lesson
        UID: 0bf2679dc61b68a5d8683c021f5e5621
        Path: /requests-and-responses/api-keys.md
      -
        Type: Lesson
        UID: 3ce410c74f7c810715f9982420878886
        Path: /requests-and-responses/sending-requests-with-python.md
      -
        Type: Instructor
        UID: 4e147331c0920ff789c815744d162587
        Path: /requests-and-responses/problem-set-requests-with-python.instructor.md
      -
        Type: Lesson
        UID: 3c6844408261fe7c7d50f7dc4dc2c447
        Path: /requests-and-responses/problem-set-requests-with-python.md
      -
        Type: Lesson
        UID: 2f8f732d3d523c2302f4568e519bcbff
        Path: /requests-and-responses/activity-web-api-jigsaw.md
