---
Standards:
  -
    Title: Update And Delete
    Description: "Update and Delete"
    UID: c806ada4c97ac6c20ee838c607c979d7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: eebc0514b2efcba42ff925c17aa17fde
        Path: /update-and-delete/update-and-delete.md
