---
Standards:
  -
    Title: Testing Our Apis
    Description: Testing Our Apis
    UID: e7cb1f63923b38e37e787f78784653ec
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: c49f1e46b7e1f26263c71173af781cea
        Path: /testing-our-apis/environments-and-env-vars.md
      -
        Type: Lesson
        UID: f153ea3be2591354fccbc62912327060
        Path: /testing-our-apis/dot-env-and-the-test-db.md
      -
        Type: Lesson
        UID: 8dfac72f68845ac31b3527aeba524c01
        Path: /testing-our-apis/fixtures.md
      -
        Type: Lesson
        UID: ae6d7749089a176f86e664172c9c3102
        Path: /testing-our-apis/test-setup.md
      -
        Type: Lesson
        UID: MAKii1
        Path: /testing-our-apis/using-tests.md
